
import "../../public/styles/theme.min.css";
import { UserContextProvider } from "../app/Context/userContext";
import { AuthProvider } from "../app/Context/AuthContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-sky-500">
        <main>
        <AuthProvider>
            <UserContextProvider>
                {children}
            </UserContextProvider>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
